language: c

cache: apt

sudo: required
dist: trusty

addons:
  apt:
    sources:
#      - ubuntu-sdk-team
    packages:
      - qtbase5-dev
      - qtdeclarative5-dev
      - libfftw3-dev

compiler:
#  - clang
  - gcc

#before_install:
#  - sudo apt-get update -q
#  - sudo apt-get install -y gnuradio qtbase5-dev libfftw3-dev libboost-all-dev

before_script:
  - pushd /tmp
  - mkdir liquid-install
  - git clone https://github.com/jgaeddert/liquid-dsp.git
  - cd liquid-dsp
  - ./bootstrap.sh
  - ./configure --prefix=/tmp/liquid-install/
  - make
  - make install
  - popd

script:
  - mkdir build
  - cd build
  - CFLAGS="-g -Wall -Wextra -Werror -Wno-zero-length-array" cmake -DLIQUID_LIBRARIES=/tmp/liquid-install/lib/libliquid.so -DLIQUID_INCLUDES=/tmp/liquid-install/include/ ..
  - make
